### ISSUE TITLE
Cannot subscribe to rss feed, cannot launch anymore

### ISSUE THREAD

**Issue by probonopd** [son-link/minimal-podcasts-player#1]
Hello @son-link, I am looking for a small Podcast player for use with [helloSystem](https://hellosystem.github.io/docs/).

When trying to subscribe to https://feeds.fireside.fm/bsdnow/rss, I get a crash:

```
% /var/run/user/1001/_home_user_Desktop_minimal-podcasts-player-master.zip/minimal-podcasts-player-master/minimal-podcasts-player      
error: XDG_RUNTIME_DIR not set in the environment.
error: XDG_RUNTIME_DIR not set in the environment.
error: XDG_RUNTIME_DIR not set in the environment.
error: XDG_RUNTIME_DIR not set in the environment.
QKqueueFileSystemWatcherEngine::addPaths: open: No such file or directory
Traceback (most recent call last):
  File "/var/run/user/1001/_home_user_Desktop_minimal-podcasts-player-master.zip/minimal-podcasts-player-master/mpp/db.py", line 38, in run
    data = parseFeed(self.url)
  File "/var/run/user/1001/_home_user_Desktop_minimal-podcasts-player-master.zip/minimal-podcasts-player-master/mpp/utils.py", line 12, in parseFeed
    with urlopen(url) as response:
  File "/usr/local/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/local/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/local/lib/python3.7/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/local/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/local/lib/python3.7/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden
zsh: abort   
```

When I then try to run the application again, it does not even start anymore:

```
% /var/run/user/1001/_home_user_Desktop_minimal-podcasts-player-master.zip/minimal-podcasts-player-master/minimal-podcasts-player
Traceback (most recent call last):
  File "/var/run/user/1001/_home_user_Desktop_minimal-podcasts-player-master.zip/minimal-podcasts-player-master/minimal-podcasts-player", line 3, in <module>
    mpp.init()
  File "/var/run/user/1001/_home_user_Desktop_minimal-podcasts-player-master.zip/minimal-podcasts-player-master/mpp/__init__.py", line 324, in init
    if config['theme'] != 'system':
KeyError: 'theme'
```

At this point, I have to delete `~/.local/share/mpp/` to be able to launch the application again.

**Comment by son-link** [comment]
Firts, thanks for using my proyect.
The first failure is because the server on receiving the request returns the HTTP status code 403, this response code indicates that the server understood the request but refuses to authorize it. Accessing from a browser the URL loads correctly, so I will test it from the program.

As for the second bug it is due to a small known bug that I will fix in the next revision and that affects when the default configuration is generated. You have to open the ~/.local/share/mpp/mpp.ini file and add this line

`theme = default`

**Comment by son-link** [comment]
This issue has been fixed pending the release of the next version.

**Comment by probonopd** [comment]
Cool. Please `git push`, thanks.

**Comment by son-link** [comment]
The new release is publised

**Comment by probonopd** [comment]
Still....
(Yes I deleted the settings file)

```
% /home/user/Desktop/bin/minimal-podcasts-player
Traceback (most recent call last):
  File "/home/user/Desktop/bin/minimal-podcasts-player", line 3, in <module>
    mpp.init()
  File "/usr/home/user/Desktop/bin/mpp/__init__.py", line 333, in init
    if config['theme'] != 'system':
KeyError: 'theme'
```

**Comment by probonopd** [comment]
If I remove all theming related code then it works:

![image](https://user-images.githubusercontent.com/2480569/111033233-71e35880-8410-11eb-8b45-bee75d648d4a.png)

**Comment by probonopd** [comment]
Would you consider to (also) license your project under a  permissive license, such as MIT or BSD 2-clause?

**Comment by son-link** [comment]
You can testing the last commit remove , or backup, the config file?
I tested on mi PC and Windows and now realy generate the default condig with the theme option

**Comment by probonopd** [comment]
Yes, I had done `rm -rf /home/user/.local/share/mpp/`, then started the application, closed the application, tried to start again. Does not work until I do `rm -rf /home/user/.local/share/mpp/` again.

**Comment by son-link** [comment]
Umm, i testing more and it's working.
Have you tested it with the latest commit or have you tested it with the latest release? Because if it's with the latest it's normal because it doesn't have the fix, I have to test it before and then create a release.

**Comment by probonopd** [comment]
Will test again.

**Comment by probonopd** [comment]
You are right, https://github.com/son-link/minimal-podcasts-player/commit/b155a9cb62a59e053788229f974f261723436504 solves it. Thank you!
