### ISSUE TITLE
Default to system theme

### ISSUE THREAD

**Issue by probonopd** [son-link/minimal-podcasts-player#3]
Please default to system theme `theme = system` and make the "System" selectable in the configuration window.

Most users want applications to look "native", and to follow the look and feel of the rest of the system (buttons, fonts, colors, etc.). In my example:

![](https://user-images.githubusercontent.com/2480569/111033233-71e35880-8410-11eb-8b45-bee75d648d4a.png)

**Comment by son-link** [comment]
I am working on it. At first there was no option to select a theme, but seeing that in both Windows and an .AppImage it defaulted to the Fusion theme I decided to look for some themes to use in both, but I couldn't get it to switch back to the system theme except by restarting the program.  I think that's the only way, so if I see that it changes from a qt-material theme to the system theme it should show a warning message about it, and if it accepts, restart.

**Comment by probonopd** [comment]
This solves it for me:
https://github.com/son-link/minimal-podcasts-player/pull/4

**Comment by son-link** [comment]
In the last commit this option is only available for Windows and .AppImage , but need some testing on boot

**Comment by probonopd** [comment]
Thanks @son-link.

Unfortunately the problems are back:

![image](https://user-images.githubusercontent.com/2480569/111669749-67153300-8817-11eb-8d11-27b7d4918d42.png)

**Comment by son-link** [comment]
Ok, i use a function for detect the system. Just i installed Hello on Virtual Machine on VirtualBox just for testing

**Comment by probonopd** [comment]
It seems like the standard colors of the system are ignored. Compare to the "Keyboard Layout" window: there the selected item font is white, which is much more readable on the black background.

![image](https://user-images.githubusercontent.com/2480569/111671793-92008680-8819-11eb-8b51-9f601a5b1c75.png)

**Comment by son-link** [comment]
In the next release i remove qt-material and replace the icons for Breeze icons for use on Windows and the AppImage.

**Comment by probonopd** [comment]
And for other OSes, such as FreeBSD?

**Comment by son-link** [comment]
> And for other OSes, such as FreeBSD?

Uses the system theme, as in Linux
