### ISSUE TITLE
Unsubscribe from podcast?

### ISSUE THREAD

**Issue by probonopd** [son-link/minimal-podcasts-player#5]
How does one unsubscribe from a podcast? I can only add...

**Comment by son-link** [comment]
This option isn't avaliable for now, but I add for the next big release.

**Comment by son-link** [comment]
This option is available click on the podcast with click mouse right button and click in the option.

**Comment by probonopd** [comment]
Thank you, this is working well for me and exactly where i'd expect the feature to be located.
