### ISSUE TITLE
Search podcasts

### ISSUE THREAD

**Issue by probonopd** [son-link/minimal-podcasts-player#6]
Please add a way to search podcasts, e.g., on iTunes.

Perhaps these are useful?
* https://github.com/nalgeon/podsearch-py
* https://github.com/tkem/mopidy-podcast

**Comment by son-link** [comment]
I am working on it. I've written some code to search using the iTunes API, since it's the only open API (I found others with some limit of uses, after which you have to pay) that I found, something that, for example, Ivoox doesn't have.

**Comment by son-link** [comment]
In the last commit I added a new dialog for adding podcasts. I upload a video to my Twitter Account for show:
https://twitter.com/sonlink/status/1372444575567085569

**Comment by probonopd** [comment]
Thank you, this seems to work well as long as you search for terms that are in the title of the podcast.

But searching e.g., "FreeBSD" does not resturn the "BSD Now" podcast.
Is there a possibility to also search in the keywords/description, so that searching for "FreeBSD" would also find the "BSD Now" podcast?

Also, it would be nice if the podcast icons could be shown like in the main window.

![image](https://user-images.githubusercontent.com/2480569/111671217-025ad800-8819-11eb-9187-b834f6640dcb.png)

**Comment by son-link** [comment]
The iTunes API by default search in all atributes (name, description, tags, etc). Maybe I should add options to mark by which to search (all, artist, tag, etc).

**Comment by probonopd** [comment]
In this case, I think it's ok as it is. Less checkboxes and options are better!
